import 'package:flutter/material.dart';

import '../models/habit.dart';
import '../models/habit_category.dart';

final List<HabitCategory> habitCategories = [
  HabitCategory(
    title: "Trending habits",
    subtitle: "Take a step in the\nright directions.",
    imagePath: "assets/images/trending1.png",
    habits: [
      Habit(
        name: "Drink Water",
        icon: Icons.local_drink.codePoint.toString(),
        color: "#B3E5FC",
        timeOfDay: "morning",
        days: "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
        currentStreak: 0,
        longestStreak: 0,
        quantity: 1,
        progress: 0,
        unit: "glass",
        hasReminder: false,
      ),
      Habit(
        name: "Read Book",
        icon: "assets/icons/book.png",
        color: "#FFCCBC",
        timeOfDay: "evening",
        days: "Mon,Wed,Fri",
        currentStreak: 0,
        longestStreak: 0,
        quantity: 1,
        progress: 0,
        unit: "pages",
        hasReminder: false,
      ),
      Habit(
        name: "Doing Yoga",
        icon: "assets/icons/yoga.png",
        color: "#C8E6C9",
        timeOfDay: "morning",
        days: "Tue,Thu,Sat",
        currentStreak: 0,
        longestStreak: 0,
        quantity: 1,
        progress: 0,
        unit: "minutes",
        hasReminder: false,
      ),
    ],
  ),
  HabitCategory(
    title: "Stay at Home",
    subtitle: "Make the most of\nyour time indoors.",
    imagePath: "assets/images/stay.png",
    habits: [
      Habit(
        name: "Meditation",
        icon: "assets/icons/meditation.png",
        color: "#D1C4E9",
        timeOfDay: "night",
        days: "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
        currentStreak: 0,
        longestStreak: 0,
        quantity: 1,
        progress: 0,
        unit: "minutes",
        hasReminder: false,
      ),
      Habit(
        name: "Journal Writing",
        icon: "assets/icons/journal.png",
        color: "#FFE0B2",
        timeOfDay: "evening",
        days: "Mon,Wed,Fri",
        currentStreak: 0,
        longestStreak: 0,
        quantity: 1,
        progress: 0,
        unit: "pages",
        hasReminder: false,
      ),
    ],
  ),
  HabitCategory(
    title: "Stay Healthy",
    subtitle: "Stay healthy with the\nright directions.",
    imagePath: "assets/images/healty.png",
    habits: [
      Habit(
        name: "Morning Run",
        icon: "assets/icons/run.png",
        color: "#FFE082",
        timeOfDay: "morning",
        days: "Mon,Wed,Fri",
        currentStreak: 0,
        longestStreak: 0,
        quantity: 1,
        progress: 0,
        unit: "km",
        hasReminder: false,
      ),
      Habit(
        name: "Eat Fruits",
        icon: "assets/icons/fruits.png",
        color: "#FFCDD2",
        timeOfDay: "afternoon",
        days: "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
        currentStreak: 0,
        longestStreak: 0,
        quantity: 1,
        progress: 0,
        unit: "servings",
        hasReminder: false,
      ),
    ],
  ),
];
