name: active
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.0
  swipeable_tile: ^2.0.1
  iconsax: ^0.0.8
  intl: ^0.18.1
  table_calendar: ^3.0.9
  lottie: ^2.7.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
 
  uses-material-design: true
  assets:
    - assets/images/banner.png
    - assets/images/sidebar_banner.png
    - assets/animations/confetti.json
    - assets/sounds/success.wav

  